force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Imporvement_Comments__c.field-meta.xml
<CustomField>
    <fullName>Imporvement_Comments__c</fullName>
    <label>improvement Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Response_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Date_Time__c</fullName>
    <label>Response Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Response_Submitter__c.field-meta.xml
<CustomField>
    <fullName>Response_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Response_Value__c.field-meta.xml
<CustomField>
    <fullName>Response_Value__c</fullName>
    <label>Response Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bad</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Happy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SurveyController.cls
/**
* @description       : 
* @author            :
* @group             : 
* @last modified on  : 12-02-2024
* @last modified by  : 
**/
public with sharing class SurveyController {
    /**
* Description: 
**/
    @AuraEnabled
    public static Id saveSurvey(String satisfactionValue, String improvementComment, String surveyFormName) {
        
        Survey_Response__c survey = new Survey_Response__c();
        survey.Response_Value__c = satisfactionValue;
        survey.Response_Date_Time__c = Datetime.now();
        
        survey.Name = 'Customer Survey Form'; //Which Survey User Filled
        
        User u = [select id, contactId from User where id = : UserInfo.getUserId()];
        
        Id getContactId = u.contactId;
        System.debug('Fetched User ContactID:'+ getContactId);
        survey.Response_Submitter__c=getContactId;
        
        // Check if improvementComment is provided and not blank
        if (String.isNotBlank(improvementComment)) {
            survey.Imporvement_Comments__c = improvementComment; 
        }
        
        //UserInfo.getUserId()
        if (Schema.sObjectType.Survey_Response__c.fields.Response_Value__c.isCreateable()&&
            Schema.sObjectType.Survey_Response__c.fields.Response_Date_Time__c.isCreateable() &&
            Schema.sObjectType.Survey_Response__c.fields.Name.isCreateable() &&
            Schema.sObjectType.Survey_Response__c.fields.Response_Submitter__c.isCreateable() && 
            Schema.sObjectType.Survey_Response__c.fields.Imporvement_Comments__c.isCreateable() ) {
                insert survey;
            }
        
        return survey.Id;
    }
}