force-app/main/default/objects/Contact/fields/Avg_Nights_per_Stay__c.field-meta.xml
<CustomField>
    <fullName>Avg_Nights_per_Stay__c</fullName>
    <label>Avg Nights per Stay</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Class__c.field-meta.xml
<CustomField>
    <fullName>Customer_Class__c</fullName>
    <label>Customer Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest1__c.field-meta.xml
<CustomField>
    <fullName>Interest1__c</fullName>
    <label>Interest 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest2__c.field-meta.xml
<CustomField>
    <fullName>Interest2__c</fullName>
    <label>Interest 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest3__c.field-meta.xml
<CustomField>
    <fullName>Interest3__c</fullName>
    <label>Interest 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lifetime_Reservations__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Reservations__c</fullName>
    <description>The total lifetime reservations completed by a Guest and provided by Data Cloud</description>
    <label>Lifetime Reservations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lifetime_Value__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Value__c</fullName>
    <description>The Guests Lifetime Value as calculated from the data in Data Cloud</description>
    <label>Lifetime Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Spend__c</fullName>
    <label>Total Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Stays__c.field-meta.xml
<CustomField>
    <fullName>Total_Stays__c</fullName>
    <label>Total Stays</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactProfileCardDetails.cls
/*
Description: This class is used to fetch details from contacts intrest and booking type which is backend controller of ConactCard Lwc Component
*/
public with sharing  class ContactProfileCardDetails {
  //This method is used for displaying member traits on ui
    @AuraEnabled(cacheable=true)
    public static List<String> getExperienceType(Id contactId){
        Set<String> bookingExpSet = new Set<String>();
        List<String> bookingTypeSetToList = new List<String>();
        
        // Fix: Use a for-loop to avoid "too many rows" exception
    	for (Booking__dlm b : [SELECT Id__c, Type__c, Contact_c__c FROM Booking__dlm WHERE Contact_c__c = :contactId]) {
        	if (b.Type__c != null && b.Type__c != '') {
            	bookingExpSet.add(b.Type__c);
        	}
    	}
        system.debug('booking filtered set'+bookingExpSet);
        /*List<Booking__dlm> bookingTypeList = [Select Id__c,Type__c,Contact_c__c from Booking__dlm where Contact_c__c =:contactId];
        system.debug('booking type list:'+bookingTypeList);
        if(bookingTypeList !=null){
            for(Booking__dlm b:bookingTypeList){
                if(b.Type__c != null || b.Type__c != ''){
                    bookingExpSet.add(b.Type__c);
                }
            }
            system.debug('booking filtered set'+bookingExpSet);
        } */
        
        List<Contact> contactIntrestList = [Select id,Interest1__c,Interest2__c,Interest3__c from Contact where id =:contactId];
        system.debug('contactIntrestList:'+contactIntrestList);
        if(contactIntrestList != null)
        {
            for(Contact c:contactIntrestList){
                if(c.Interest1__c != null || c.Interest1__c != ''){
                    bookingExpSet.add(c.Interest1__c);
                }
                 if(c.Interest2__c != null || c.Interest2__c != ''){
                    bookingExpSet.add(c.Interest2__c);
                }
                 if(c.Interest3__c != null || c.Interest3__c != ''){
                    bookingExpSet.add(c.Interest3__c);
                }
            }
        }
        if(!bookingExpSet.isEmpty()){
            bookingTypeSetToList.addAll(bookingExpSet); 
        }
        system.debug('Booking Type Set to List:'+bookingTypeSetToList);
        return bookingTypeSetToList;
    }
    

    //Method for getting Calculated insight value
    @AuraEnabled(cacheable=true)
    public static Contact getGuestCalculatedInsights(Id contactId){
        try {
            Contact  con = [SELECT FirstName,LastName,Customer_Class__c,Lifetime_Value__c,Total_Stays__c,Total_Room_Nights__c,Total_Spend__c,Avg_Nights_per_Stay__c,Lifetime_Reservations__c FROM Contact WHERE Id=:contactId LIMIT 1] ;
            return con;
        }catch(Exception e){
            system.debug('Error:'+e.getMessage());
            return null;
        }
         

    }

}