force-app/main/default/objects/Contact/fields/Interest1__c.field-meta.xml
<CustomField>
    <fullName>Interest1__c</fullName>
    <label>Interest 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest2__c.field-meta.xml
<CustomField>
    <fullName>Interest2__c</fullName>
    <label>Interest 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest3__c.field-meta.xml
<CustomField>
    <fullName>Interest3__c</fullName>
    <label>Interest 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <description>Categorizes the experience based on its physical intensity or required skill level, with values ranging from &quot;Low&quot; for relaxed activities to &quot;High&quot; for more vigorous or skill-intensive experiences.</description>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Defines the maximum number of participants that can be accommodated in a single session of the experience, ensuring optimal guest enjoyment and safety.</description>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Default_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Default_Start_Time__c</fullName>
    <description>The default start time used to build the schedule each day</description>
    <label>Default Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Provides a detailed overview of the experience, including what guests can expect, any prerequisites or recommendations, and unique highlights that distinguish this activity or service.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The Price__c field indicates the cost associated with participating in an experience, allowing guests to understand the financial commitment for each activity and enabling the resort to manage and display pricing information for its offerings.</description>
    <label>Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>The average Guest Rating</description>
    <formula>Sum_of_Guest_Reviews__c / Total_Guest_Reviews__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <description>Calculates the number of slots still available for booking by subtracting the Booked_Slots__c from the Capacity__c, offering real-time availability data.</description>
    <formula>Capacity__c - Booked_Slots__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Booked_Slots__c.field-meta.xml
<CustomField>
    <fullName>Booked_Slots__c</fullName>
    <description>Tracks the number of slots already booked by guests for the experience, aiding in reservation management.</description>
    <label>Booked Slots</label>
    <summarizedField>Booking__c.Number_of_Guests__c</summarizedField>
    <summaryFilterItems>
        <field>Booking__c.Is_Canceled__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Session__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Experience__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Marks the concluding time of the experience instance, ensuring clear communication to guests about the duration of activities.</description>
    <formula>Start_Time__c + (Experience__r.Duration_Hours__c* 3600000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience_Name__c.field-meta.xml
<CustomField>
    <fullName>Experience_Name__c</fullName>
    <description>The name of the experience</description>
    <formula>Experience__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Experience Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Percentage_Booked__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Booked__c</fullName>
    <description>The percentage of available slots.</description>
    <formula>Booked_Slots__c / Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Booked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Indicates the beginning time of the experience instance, helping guests plan their day around scheduled activities.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status field tracks the current state of an experience booking, indicating whether it is Confirmed, Canceled, or Completed. This field is essential for managing reservations effectively, allowing both resort staff and guests to understand the booking&apos;s progression from confirmation through completion or cancellation, facilitating clear communication and operational planning.</description>
    <formula>IF(Is_Canceled__c , &quot;Canceled&quot;, IF( Date__c &gt;= Today(), &quot;Confirmed&quot;, &quot;Completed&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExperienceController.cls
public with sharing class ExperienceController {
    static Integer PAGE_SIZE = 9;
    
    public static List<Experience_c__dlm> getExperienceRecords(Contact contact) {
        System.debug('## contact Exp = '+contact);       
        List<Experience_c__dlm> listOfExperiences = new List<Experience_c__dlm>();
        if(contact != NULL){
            String intrest1 =   contact.Interest1__c;
            String intrest2 =   contact.Interest2__c;
            String intrest3 =   contact.Interest3__c;
            if(intrest1 == NULL && intrest2 == NULL && intrest3 == NULL){
                intrest1 = 'Adventure Activities';
            }
            listOfExperiences = [
                SELECT
                Id__c,
                Name__c,
                Type_c__c,
                Price_c__c,
                Picture_URL_c__c,
                Activity_Level_c__c,
                Duration_Hours_c__c,
                Capacity_c__c
                FROM Experience_c__dlm Where  Type_c__c IN (:intrest1, :intrest2, :intrest3) 
                ORDER BY CreatedDate__c DESC
                LIMIT 100
            ];
            System.debug('## listOfExperiences = '+listOfExperiences);
            System.debug('## listOfExperiences size = '+listOfExperiences.size());            
        }
        return listOfExperiences;
    }
    
    public static List<Booking__dlm> getExperienceBookingsRecords(Contact contact) {
        System.debug('## contact Exp = '+contact); 
        List<Booking__dlm> listOfBookings = new List<Booking__dlm>();
        if(contact != NULL){
            String intrest1 =   contact.Interest1__c;
            String intrest2 =   contact.Interest2__c;
            String intrest3 =   contact.Interest3__c; 
            if(intrest1 == NULL && intrest2 == NULL && intrest3 == NULL){
                intrest1 = 'Adventure Activities';
            }
            List<Experience_c__dlm> listOfExperiences = [
                SELECT
                Id__c,
                Name__c,
                Type_c__c,
                Price_c__c,
                Picture_URL_c__c,
                Activity_Level_c__c,
                Duration_Hours_c__c,
                Capacity_c__c
                FROM Experience_c__dlm Where  Type_c__c IN (:intrest1, :intrest2, :intrest3)
                ORDER BY CreatedDate__c DESC
                LIMIT 20
            ];
            Set<String> setOfExpName = new Set<String>();
            If(!listOfExperiences.isEmpty()){
                for(Experience_c__dlm exp : listOfExperiences){
                    setOfExpName.add(exp.Name__c);
                }
            }else{
                setOfExpName.add('White Water Rafting Rush');
            }
            System.debug('## setOfExpName = '+setOfExpName);  
            
            
            listOfBookings = [
                Select Id__c,Session_c__c,Activity_Level__c,Number_of_Guests__c,Experience_Name__c,Type__c,
                Total_Price__c
                from Booking__dlm Where 
                Contact_c__c =:  contact.Id and Experience_Name__c IN : setOfExpName  
                ORDER BY CreatedDate__c DESC
                LIMIT 20
            ];
            System.debug('## listOfBookings = '+listOfBookings);
            System.debug('## listOfBookings size = '+listOfBookings.size());
    	}
        return listOfBookings;
    }
    
    public static List<Experience_Session__dlm> getExperienceSessionRecordsForUpcoming(Contact contact) {
        System.debug('## contact Sess = '+contact);
		String intrest1 =   contact.Interest1__c;
        String intrest2 =   contact.Interest2__c;
        String intrest3 =   contact.Interest3__c;
        List<Experience_c__dlm> listOfExperiences = [
            SELECT
            Id__c,
            Name__c,
            Type_c__c,
            Price_c__c,
            Picture_URL_c__c,
            Activity_Level_c__c,
            Duration_Hours_c__c,
            Capacity_c__c
            FROM Experience_c__dlm Where  Type_c__c IN (:intrest1, :intrest2, :intrest3)
            ORDER BY CreatedDate__c DESC
            LIMIT 100
        ];
        Set<Id> idOfExp = new Set<Id>();
        If(!listOfExperiences.isEmpty()){
            for(Experience_c__dlm exp : listOfExperiences){
                idOfExp.add(exp.Id__c);
            }
        }
        System.debug('## idOfExp = '+idOfExp);        
        List<Experience_Session__dlm> listOfSessions = new List<Experience_Session__dlm>();
        if(idOfExp != null){
            listOfSessions = [
                Select Id,Id__c,Name__c,Date__c,Start_Time__c,End_Time__c,
                Experience__c
                from Experience_Session__dlm Where Experience__c IN : idOfExp and Date__c = Today 
                ORDER BY Date__c DESC
                LIMIT 50
        	];
        }         
        System.debug('## listOfSessions Sess = '+listOfSessions);
        System.debug('## listOfSessions Sess size = '+listOfSessions.size());
        return listOfSessions;
    }
    
    public static List<Session__c> getExperienceSessionRecordsForPast(Contact contact) {
        System.debug('## contact Sess = '+contact);
        List<Experience__c> listOfExperiences = [
            SELECT
            Id,
            Name,
            Type__c,
            Price__c,
            Activity_Level__c,
            Default_Start_Time__c,
            Capacity__c
            FROM Experience__c
            WHERE
            (Type__c = :contact.Interest1__c
             OR Type__c = :contact.Interest2__c
             OR Type__c = :contact.Interest3__c)
            WITH USER_MODE
            ORDER BY CreatedDate DESC
            LIMIT 100
        ];
        Set<Id> idOfExp = new Set<Id>();
        If(!listOfExperiences.isEmpty()){
            for(Experience__c exp : listOfExperiences){
                idOfExp.add(exp.Id);
            }
        }
        System.debug('## idOfExp = '+idOfExp);
        List<Session__c> listOfSessions = new List<Session__c>();
        if(idOfExp != null){
            listOfSessions = [
                Select Id,Name,Date__c,Start_Time__c,
                End_Time__c,Available_Slots__c,Percentage_Booked__c,Experience__c,Experience__r.Name
                from Session__c Where Experience__c IN : idOfExp and Date__c < Today
                WITH USER_MODE
                ORDER BY CreatedDate DESC
                LIMIT 100
        	];
        }         
        System.debug('## listOfSessions Sess = '+listOfSessions);
        System.debug('## listOfSessions Sess size = '+listOfSessions.size());
        return listOfSessions;
    }

    /**
     * Endpoint that retrieves the sessions associated with an experience and a date
     * @param experienceId Experience ID
     * @param timestamp Timestamp representing the date on which the sessions take place
     * @return List of Session__c records
     */
    @AuraEnabled(cacheable=true scope='global')
    public static List<Session__c> getExperienceSessionsForDate(
        Id experienceId,
        Long timestamp
    ) {
        Date dateFilter = Datetime.newInstance(timestamp).date();
        List<Session__c> sessions = [
            SELECT
                Id,
                Booked_Slots__c,
                Capacity__c,
                End_Time__c,
                Percentage_Booked__c,
                Start_Time__c,
                Status__c,
                Experience__r.Price__c
            FROM Session__c
            WHERE Experience__c = :experienceId AND Date__c = :dateFilter
            WITH SECURITY_ENFORCED
            ORDER BY Start_Time__c ASC
            LIMIT 10
        ];
        return sessions;
    }

    @AuraEnabled(Cacheable=true scope='global')
    public static PagedResult getExperiences(String type, Integer pageNumber) {
        String whereClause = '';
        if (type != null || type != '') {
            whereClause = 'WHERE Type__c = :type';
        }
        Integer pageSize = ExperienceController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM Experience__c ' + whereClause
        );
        result.records = Database.query(
            'SELECT Id, Name, Description__c, Rating__c, Picture_URL__c FROM Experience__c ' +
                whereClause +
                ' WITH SECURITY_ENFORCED' +
                ' ORDER BY Name LIMIT :pageSize OFFSET :offset'
        );
        return result;
    }

    public with sharing class PagedResult {
        @AuraEnabled
        public Integer pageSize { get; set; }
    
        @AuraEnabled
        public Integer pageNumber { get; set; }
    
        @AuraEnabled
        public Integer totalItemCount { get; set; }
    
        @AuraEnabled
        public Object[] records { get; set; }
    }
    
}